BlogTrackerProject/Controllers/AdminLoginController.cs
using BlogTrackerProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace BlogTrackerProject.Controllers
{
    public class AdminLoginController : Controller
    {
        // GET: Adminsignin
        // GET: AdminSignIn
        SqlConnection con = new SqlConnection();
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;
        // GET: EmpSignin
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        void connectionString()
        {
            con.ConnectionString = "Server=tcp:capstonedb.database.windows.net,1433;Initial Catalog=CapstoneDb;Persist Security Info=False;User ID=onkar;Password=ManishPavan@333;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";

        }
        [HttpPost]
        public ActionResult Verify(AdminInfo adm)
        {
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "select * from AdminInfo where EmailId='" + adm.EmailId + "' and Password='" + adm.Password + "'";
            dr = com.ExecuteReader();

            if (dr.Read())
            {
                con.Close();
                return RedirectToAction("Index", "Employeeinfo"); // Assuming EmployeeInfo is your controller name
            }
            else
            {
                con.Close();
                return RedirectToAction("Index", "Bloginfo");  // Assuming "Home" is the name of the view you want to return in case of failure
            }
        }

    }
}

BlogTrackerProject/Controllers/BloginfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogTrackerProject.Models;

namespace BlogTrackerProject.Controllers
{
    public class BloginfoController : Controller
    {
        private readonly CapstoneDbContext _context;

        public BloginfoController(CapstoneDbContext context)
        {
            _context = context;
        }

        // GET: Bloginfo
        public async Task<IActionResult> Index()
        {
            var capstoneDbContext = _context.Bloginfos.Include(b => b.EmpemailNavigation);
            return View(await capstoneDbContext.ToListAsync());
        }
        public async Task<IActionResult> HomeDisplay()
        {
            var capstoneDbContext = _context.Bloginfos.Include(b => b.EmpemailNavigation);
            return View(await capstoneDbContext.ToListAsync());
        }

        // GET: Bloginfo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Bloginfos == null)
            {
                return NotFound();
            }

            var bloginfo = await _context.Bloginfos
                .Include(b => b.EmpemailNavigation)
                .FirstOrDefaultAsync(m => m.Blogid == id);
            if (bloginfo == null)
            {
                return NotFound();
            }

            return View(bloginfo);
        }

        // GET: Bloginfo/Create
        public IActionResult Create()
        {
            ViewData["Empemail"] = new SelectList(_context.Employeeinfos, "Emailid", "Emailid");
            return View();
        }

        // POST: Bloginfo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Blogid,Title,Subject,DateOfCreation,Blogurl,Empemail")] Bloginfo bloginfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bloginfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Empemail"] = new SelectList(_context.Employeeinfos, "Emailid", "Emailid", bloginfo.Empemail);
            return View(bloginfo);
        }

        // GET: Bloginfo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Bloginfos == null)
            {
                return NotFound();
            }

            var bloginfo = await _context.Bloginfos.FindAsync(id);
            if (bloginfo == null)
            {
                return NotFound();
            }
            ViewData["Empemail"] = new SelectList(_context.Employeeinfos, "Emailid", "Emailid", bloginfo.Empemail);
            return View(bloginfo);
        }

        // POST: Bloginfo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Blogid,Title,Subject,DateOfCreation,Blogurl,Empemail")] Bloginfo bloginfo)
        {
            if (id != bloginfo.Blogid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bloginfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BloginfoExists(bloginfo.Blogid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Empemail"] = new SelectList(_context.Employeeinfos, "Emailid", "Emailid", bloginfo.Empemail);
            return View(bloginfo);
        }

        // GET: Bloginfo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Bloginfos == null)
            {
                return NotFound();
            }

            var bloginfo = await _context.Bloginfos
                .Include(b => b.EmpemailNavigation)
                .FirstOrDefaultAsync(m => m.Blogid == id);
            if (bloginfo == null)
            {
                return NotFound();
            }

            return View(bloginfo);
        }

        // POST: Bloginfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Bloginfos == null)
            {
                return Problem("Entity set 'CapstoneDbContext.Bloginfos'  is null.");
            }
            var bloginfo = await _context.Bloginfos.FindAsync(id);
            if (bloginfo != null)
            {
                _context.Bloginfos.Remove(bloginfo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BloginfoExists(int id)
        {
          return (_context.Bloginfos?.Any(e => e.Blogid == id)).GetValueOrDefault();
        }
    }
}

BlogTrackerProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogTrackerProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogTrackerProject.styles.css" asp-append-version="true" />
    <!-- Add these lines to your head section -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="...">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="..."></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="..."></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="..."></script>

    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogTrackerProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                               Login
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AdminLogin" asp-action="Login">Admin</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeLogin" asp-action="Login">Employee</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BlogTrackerProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogTrackerProject/Views/Shared/_LayoutBlog.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogTrackerProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogTrackerProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bloginfo" asp-action="Index">Blog-List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bloginfo" asp-action="HomeDisplay">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BlogTrackerProject/Views/Shared/_LayoutEmplist.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BlogTrackerProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogTrackerProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employeeinfo" asp-action="Index">Employee list</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bloginfo" asp-action="HomeDisplay">Log-out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>